"""change constraints

Revision ID: 2fcde992fcac
Revises: adc34179983e
Create Date: 2024-12-07 18:25:30.129586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcde992fcac'
down_revision: Union[str, None] = 'adc34179983e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Unique username of the user')
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Role of the user (e.g., admin, player, etc.)')
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment="User's first name")
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment="User's last name")
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Age of the user (must be greater than 0)')
    op.alter_column('user', 'experience',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Years of experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Hashed password of the user'))
    op.alter_column('user', 'experience',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Years of experience')
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Age of the user (must be greater than 0)')
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment="User's last name")
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment="User's first name")
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Role of the user (e.g., admin, player, etc.)')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Unique username of the user')
    # ### end Alembic commands ###
