"""add link model

Revision ID: fae79ac7107a
Revises: 9ccfa95fc6c7
Create Date: 2024-12-25 23:00:40.375540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae79ac7107a'
down_revision: Union[str, None] = '9ccfa95fc6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_link',
    sa.Column('link', sa.Text(), nullable=True, comment='Link for telegram bot'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of the user who left the link'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_link')
    # ### end Alembic commands ###
