name: match_maker

x-common: &x-common
  image: local/match_maker
  build:
    context: .
  env_file:
    - ./.env
  networks:
    - match_maker

services:

  postgresql:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - match_maker

networks:
  match_maker:
    driver: bridge
